name: Release
description: Release a new npm package
inputs:
  npm:
    description: npm token
    required: true
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Set node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm
    - name: Publish to NPM
      run: |
        pnpm config set //registry.npmjs.org/:_authToken ${{ inputs.npm }}
        pnpm publish --access public --no-git-checks
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm }}
