name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          include-v-in-tag: false
      - if: ${{ steps.release.outputs.releases_created }}
        uses: ./.github/actions/release
        with:
          npm: ${{ secrets.NPM_TOKEN }}
